### ISSUE TITLE
FEATURE REQUEST: Use normal units and not static units

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#10]
**FEATURE REQUEST**
Build: Timestamp: 04.03.2020 23:12:30.82 
Mission: https://www.dropbox.com/s/9q3a6sugjgpq1dz/Neck_Skynet_test_v2.miz?dl=0

Currently it is not possible to use a normal unit for node or powersupply. (See screenshot below after node have been destroyed and after powersupply have beend destroyed).

Would it be possible to use a normal unit for node or powersupply?

Node
![bilde](https://user-images.githubusercontent.com/26002570/75976055-f637fd00-5ed9-11ea-89f6-fcf7b2f12a55.png)

Powersupply:
![bilde](https://user-images.githubusercontent.com/26002570/75976144-21bae780-5eda-11ea-92f3-2ac7e039ddd9.png)

**Comment by walder** [comment]
Already on the Kanban to be investigated:
https://github.com/walder/Skynet-IADS/projects/1

False product claim in the documentation 😄 

Oh and there is a new build of the script with multiple fixes.
