### ISSUE TITLE
BUG: Error when node gets destroyed (static object ground vehicle vs static object structures)

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#11]
**BUG**
Build: Timestamp: Timestamp: 04.03.2020 23:12:30.82  
Missionfile: https://www.dropbox.com/s/near828hhn50a90/Neck_Skynet_test_v3.miz?dl=0
Linked issues: Issue #6 

In SAM group 1, I made the powersupply and node to a static object: Ground vehicles  
and for SAM ground 2 powersupply and node to static object: Structures
With the latest build, I can destroy one unit as the screenshot shows
![bilde](https://user-images.githubusercontent.com/26002570/76009285-42eafa80-5f11-11ea-9176-6607c9403b63.png)

But when I attack unit number 2 or 3 I get the following error:

![bilde](https://user-images.githubusercontent.com/26002570/76009036-da9c1900-5f10-11ea-8145-bdf32ada6972.png)

![bilde](https://user-images.githubusercontent.com/26002570/76009483-8fced100-5f11-11ea-8204-ec11465abab2.png)

![bilde](https://user-images.githubusercontent.com/26002570/76009598-bee54280-5f11-11ea-97e7-bbc165ca7ac8.png)

However, when I make both SAM groups to use powersupply and node to static object: Structures
Then I do not get any errors when they are destroyed.

![bilde](https://user-images.githubusercontent.com/26002570/76010135-b04b5b00-5f12-11ea-851b-4d1d004dfdd4.png)

![bilde](https://user-images.githubusercontent.com/26002570/76010227-d8d35500-5f12-11ea-8b60-539141ba9989.png)

**Comment by walder** [comment]
fixed locally, will deploy once tests are updated

**Comment by walder** [comment]
just added a new build, loaded it in to your misssion, no errors anymore on my side.  Also found another bug regarding a false warning if you named a non SAM unit with the same prefix as you planned loading in to the IADS.
