### ISSUE TITLE
FEATURE REQUEST: Close protection SAM

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#13]
**FEATURE REQUEST:**

Would it be possible to connect another component to the IADS, specificly an option similar to node and powersupply to each specific site.
I am thinking about a close protection SAM (SA-15/SA-19) connected to the larger SAMs and if a HARM is shot against the site, then the close protection SAM comes online to shoot down the HARM.

Rationale: The larger SAMs such as SA-2 and SA-3 are likely more static, and are of higher value, and need protection to increase survivability.

**Comment by walder** [comment]
That already works, check out the updated demo mission and choose the SA-10 attack slot.

The SA-10 currently does not engage HARMs in DCS regardless of the options you set.

I placed a SA15 east of the SA-10. As soon as the HARM is detected by the IADS and in range of the SA-15 it will go live and shoot at the HARM.

Granted much of what I described is already in the default DCS code. I just make sure the SA-15 goes live only when an object in the AIR is in its range. Im quite sure the SA-15 would also go for Mavericks and Bombs, but I will have to test that.
