### ISSUE TITLE
AMMO## Static object work around

### ISSUE THREAD

**Issue by alcmann** [walder/Skynet-IADS#14]
Noticing script call can use 
local commandCenter = StaticObject.getByName("Command Center2")
local comPowerSource = StaticObject.getByName("Command Center2 Power Source")
iranianIADS:addCommandCenter(commandCenter, comPowerSource)

This is used for a command center and its associated power source, however with the recent ME bug with renaming all static objects to AMMO##

Is it possible to use regular units and call on them instead of a static object in the mission editor ? 

for example 
local commandCenter = Unit.getByName("Command Center2")

Would this work ? sorry i am very weak on my lua skills

this will get around the DCS Bug in the meantime ?

**Comment by walder** [comment]
Thanks for your testing Skynet. You will get 10% off on your next Terminator purchase.

It works, you can use:
local commandCenter = Unit.getByName("Command Center2")

Provided there is a unit this said name in the mission.
