### ISSUE TITLE
Debug menu on or off Command while Miz is running

### ISSUE THREAD

**Issue by alcmann** [walder/Skynet-IADS#15]
Greetings

Is there a way to turn on/off in game the Debug menu ? 

Have tried with triggers running script with 

for **DEBUG ON**I have been using your provided debug 
do
iranIADS = SkynetIADS:create()

---debug settings remove from here on if you do not wan't any output on what the IADS is doing
local iadsDebug = iranIADS:getDebugSettings()
iadsDebug.IADSStatus = true
iadsDebug.samWentDark = true
iadsDebug.contacts = true
iadsDebug.radarWentLive = true
iadsDebug.noWorkingCommmandCenter = true
iadsDebug.ewRadarNoConnection = true
iadsDebug.samNoConnection = false
iadsDebug.jammerProbability = true
iadsDebug.addedEWRadar = false
iadsDebug.hasNoPower = false
---end remove debug ---

For DEBUG OFF i created another script to run on a trigger however it doesnt work or shut off the notification in the top right corner
------------------------------------------------------------
iranIADS:addEarlyWarningRadarsByPrefix('EW')
iranIADS:addSamSitesByPrefix('SAM')

local iadsDebug = iranIADS:getDebugSettings()
iadsDebug.IADSStatus = false
iranIADS:activate()

---------------------------------------------------------

Do you know of a way i can shut the debug off while the mission is live and running to turn it off or on again ? 

thanks

**Comment by walder** [comment]
Thanks, good Idea. I will add a menu option to the IADS in the next release. Before I add that I want to improve some of the core logic

**Comment by walder** [comment]
Hi @alcmann the latest compiled script has a radio menu option. See the Reame.md on how to activate it. Have fun!
