### ISSUE TITLE
Node script

### ISSUE THREAD

**Issue by zelchy** [walder/Skynet-IADS#16]
the connection node script to add a node for EWR is unclear??

local connectionNode = Unit.getByName("EW connection node") 
ewRadar:addConnectionNode(connectionNode)

I don't understand how to add the EW name? where? I have tried to install NODES to my EWR in a 
test game but keep getting errors like this

[string .......... 788a.I..."]:38:'='expected near'-'

can you clarify?

**Comment by walder** [comment]
First setup the IADS:

redIADS = SkynetIADS:create()
redIADS:addSamSitesByPrefix('SAM')
redIADS:addEarlyWarningRadarsByPrefix('EW')

----Then use this call to get the EW radar you want to add the connection node:
redIADS:getEarlyWarningRadarByUnitName('EW-west')

--- add the connection node:
local connectionNode = Unit.getByName("EW connection node")
ewRadar:addConnectionNode(connectionNode)

--start the IADS:
redIADS:activate()

Does that work?

I will ad more examples in the coming days.

**Comment by zelchy** [comment]
THNX @walder 
it's crystal clear now
I didn't understand how to identify the EW i wanted to add the node to
THNX

**Comment by walder** [comment]
you are welcome. I updated the docs to hopefully make that more clear. 👍
