### ISSUE TITLE
FEATURE REQUEST: Add AWACS as  EW Radar

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#17]
Would it be possible to add an Airborne AWACS (A-50 in red side)  as a participant to the IADS, similar to EW Radar?

That way, this could be used as a high value target, and will drive tactic, as the AWACS will have a lock down ability to aid the EW radars.

**Comment by walder** [comment]
Have thought about that too, should work with minor adjustements to the code. Will add it in a later release would like to finish HARM Defence first.

**Comment by 132ndNeck** [comment]
Great! Thank you very much!

**Comment by walder** [comment]
I added The A-50 Mainstay today, will finish some internal testing, an make a note in the release notes once done.
