### ISSUE TITLE
BUG: If a AC is within the SAM zone, and not detected by radar , will not zeroize

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#18]
I think I may have seen a bug.

When an aircraft is detcted by a SAM or EW, it will stay in even when it is not detected by radar as long as it stays withing the SAM WEZ.

Examples shown below:
Setup:
One EW , 2 SAM sites, and one AC:
![bilde](https://user-images.githubusercontent.com/26002570/78458235-13feaa80-76b0-11ea-967e-2d4bc1659ade.png)

F-16 in a valley without beeing detected by any radar, but it will not be forgotten until it is outside the SAM WEZ. 
![bilde](https://user-images.githubusercontent.com/26002570/78458254-3d1f3b00-76b0-11ea-9e4a-acfa4557ee66.png)

Now outside the SAM WEZ, and it starts the counter:
![bilde](https://user-images.githubusercontent.com/26002570/78458301-8ff8f280-76b0-11ea-9eb4-3a7ceeaa54df.png)

This creates a challenge, as it is not enough to avoid radar detection to be forgotten by the IADS, the pilot also need to fly outside the WEZ and not get detected by any radar

**Comment by walder** [comment]
It's not a bug that's a feature ;-)

Its a first part of the implementation of flight path interpolation. The target stays in the IADS up to 32 seconds. Later on it will extrapolate the flight path based on the last known speed, altitude and heading so even if you go low to evade radar, the IADS will have an idea where you are.
