### ISSUE TITLE
No an issue, install questions

### ISSUE THREAD

**Issue by Tinchus2009** [walder/Skynet-IADS#22]
Hello. Im starting to build campaigns, and I was looking something like your scripts. They look awesome!
Im not really skilled in scripting so Im sorry if my questions are a little bumb .

To use your scritps:
.- where Im suposed to put all the contects I download from here, in wich DCS folder should I put the files?
.- when loading the script as your instructios say, in the example the file skynet-iads-setup-persian-gulf.lua is loaded. This file has to be created from scractch for every mission file or at leat I have to create a new one and use that as templete. I can put thiis lua file anywhere and just pint it in the path in the DCS trigger screen? What about the skynet-iads-compiled.lua, what it is used for and where should I place it? Do I need to change anything in this file or it is suposed to be used without any changes?
.- To run the example mission file and I have opend the mision in the mission editor and looked for the lua files so the correct path is there. But when loading the mision, The sim just stays there trying to load the file (I have the persion gulf map, and I have the su-33 mod). What Im doing wrong?
.- May be my problem is with the MIST installation, I dont know where to place those files either, I guess I have to ask them about this but if you can tell me, THANKS

Thanks in advance for the help

**Comment by walder** [comment]
Hi this, section on GitHub is to report bugs.

I recommend you join the discord group: https://discord.gg/rE7yRJ 
There are a lot of avid Skynet Mission builders there that will help you getting started.

**Comment by Tinchus2009** [comment]
Hi. The problem is I have already tried it. But everytime I received a  message saying :invite is invalid" and I cant get into the channel.
