### ISSUE TITLE
Skynet unable to handle SA-2 and SA-3 groups.

### ISSUE THREAD

**Issue by Tebro** [walder/Skynet-IADS#28]
When loading in the mission there is a message saying that it is a unknown type and will not be managed.

**Comment by walder** [comment]
Make sure you add the P19 Search radar to a SA2 or SA3 group, see:
https://forums.eagle.ru/showthread.php?t=221022

I made it mandatory because without it the SA2 and 3 pretty much can't detect a target, making them useless in DCS.
