### ISSUE TITLE
self point defense for mixed SAM groups?

### ISSUE THREAD

**Issue by DanAlbert** [walder/Skynet-IADS#32]
https://github.com/walder/Skynet-IADS#point-defence-1

Is it feasible for skynet to enable the point defense behaviors for a group if the group contains point defense types? We're looking in to enabling point defense behavior for Liberation, and it'd be simpler if we could add SA-15s to our SA-10 groups rather than needing to work out which randomly generated group is the point defense for another. Not at all impossible for us, but seems like it'd be a helpful feature for other skynet users too assuming it's feasible.

**Comment by walder** [comment]
Skynet toggles the AI of a group to turn SAM sites on and off. As far as I know the lua scripting API this is the best method for reaction time, lower cpu usage and harm defence. So if the SA-15 would be in the group of the SAM site it would also turn off once a command is given to shut down the SAM site.

So for the moment its not possible to put pd and the SAM site in the same group.

**Comment by DanAlbert** [comment]
> So if the SA-15 would be in the group of the SAM site it would also turn off once a command is given to shut down the SAM site.

I spent a bit of time looking through the code last night and yeah, it looks like what I'm asking for would be a difference in behavior. Currently point defenses only turn on when the main site turns off, and vice versa.

What I was thinking before figuring that out was to activate both togethe, and avoid shutting down the sitewhen something the PD could defend against was inbound. That's different though, and worse than the current behavior IMO.

> What is the issue you guys have placing to groups next to each other vs adding a unit to an existing group?

It's more difficult for randomly generated missions (DCS Liberation, in this case) because we need to avoid spawning groups on top of each other, and we need to re-associate the PD group with the main group at mission load time. It's solvable, just will take us a little longer to complete than if we could just add the SA-15 to the same group.

But it'd be different and worse behavior to do it that way, so closing.

**Comment by walder** [comment]
> What I was thinking before figuring that out was to activate both togethe, and avoid shutting down the sitewhen something the PD could defend against was inbound. That's different though, and worse than the current behavior IMO.

Have you looked in to:
https://github.com/walder/Skynet-IADS#point-defence-1

_Will prevent the EW radar or SAM site from going dark if a HARM is inbound. Conditions are HARM saturation level is not reached and the point defence has ammo left. Default state is false:_

`ewRadarOrSamSite:setIgnoreHARMSWhilePointDefencesHaveAmmo(true)`


Im a bit indecisive how useful the PD feature is in Skynet currently. HARMS are picked up by the EW radar in game a long way out. Most likely that would not be the case IRL. Though I have read the rocket plasma is detectable by radar form a long distance while the motor burns. But thats definitely not simulated in DCS at the moment.

Once the HARM flies in to the engagement range of the PD it will activate anyway. HARM reaction by a SAM site is simulated by Skynet only in the terminal phase of the missile once an impact point can be calculated, basically when the nose of the missile is pointing to the ground if the impact will be within 100 m of a radar it will shut down. You can also also point an aircrat directly at the Radar when Skynet is active it will react the same.

The only benefit at the moment is that the SAM is aware of how many PDs it has and therefore will stay online as long as it believes the PDs will be able to handle the HARMs inbound, when `setIgnoreHARMSWhilePointDefencesHaveAmmo` is set. 

Besides I am thinking of writing an autodetect function for the IADS. A user of the script would need only to add the coalition. The autodetect could also add PDs to a SAM site if it is close enough. That would save you guys from needing to build an association. However you would still need to place the PDs close to the sam site when generating the groups.
