### ISSUE TITLE
SA-10 in autonomous mode turns off and never back on

### ISSUE THREAD

**Issue by DanAlbert** [walder/Skynet-IADS#33]
[skynet bugreport.miz](https://github.com/walder/Skynet-IADS/files/5727932/skynet.bugreport.miz.txt) is a mission containing one SA-10 site (search radar is the first unit, has two SRs, two TRs, a CP, and 7 launchers). There are no EWRs and this site is expected to operate in autonomous mode.

An AI F-16 will overfly the SAM.

The site briefly turns on because of `iads:setupSAMSitesAndThenActivate()`, but then turns off and never turns back on (using `activate()` does not fix the problem). https://github.com/walder/Skynet-IADS#autonomous-mode-options says that SAM sites should remain on by default when going into autonomous mode.

This is using the latest version of skynet and mist from the skynet release.

Skynet configured using:

```
iads = SkynetIADS:create("IADS")
local iadsDebug = iads:getDebugSettings()
iadsDebug.IADSStatus = true
iadsDebug.samWentDark = true
iadsDebug.contacts = true
iadsDebug.radarWentLive = true
iadsDebug.noWorkingCommmandCenter = true
iadsDebug.ewRadarNoConnection = true
iadsDebug.samNoConnection = true
iadsDebug.jammerProbability = true
iadsDebug.addedEWRadar = true
iadsDebug.hasNoPower = true
iadsDebug.harmDefence = true
iadsDebug.samSiteStatusEnvOutput = true
iadsDebug.earlyWarningRadarStatusEnvOutput = true

iads:addEarlyWarningRadarsByPrefix("RED|EWR|")
iads:addSAMSitesByPrefix("RED|SAM|")
iads:addRadioMenu()
iads:setupSAMSitesAndThenActivate()
```

[Tacview-20201221-212106-DCS-skynet bugreport.zip.acmi](https://github.com/walder/Skynet-IADS/files/5727939/Tacview-20201221-212106-DCS-skynet.bugreport.zip.acmi.txt)

**Comment by walder** [comment]
thanks will look into it.

**Comment by DanAlbert** [comment]
> The way it is currently coded there should be at least one EW radar or SAM site in EW mode.

Just to clarify, this is a majorly reduced example from a full mission where there were EWR sites present, just outside the range of this SAM. Other SAMs were operating correctly (they weren't autonomous), but this one behaved the same as it does with no EWRs anywhere.

Workaround will still work for us though. We can just set that mode on any SAM not in range of an EWR to force autonomous mode. Thanks for the suggestion 👍

**Comment by walder** [comment]
Happy new year @DanAlbert 

Thanks for reporting, It's fixed in the dev branch and will be part of the next release. Autonomous SAMs with State DCS_AI will stay active.

**Comment by DanAlbert** [comment]
Excellent, I've definitely missed being able to play liberation with skynet :)

Unsure how your release schedule works. Any timeline on the next release? If no plan yet, do you think it'd be wise for us to pull the development branch version for liberation? Not sure how stable the dev branch currently is.

**Comment by walder** [comment]
I have a release planed for tomorrow, almost finished integrating the HighDigitSAMs ;-)
