### ISSUE TITLE
QUESTION/REQUEST: SAM Traps

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#4]
First of all, thank you for your great work.

I have a question or request. When working on our missions in the 132nd Virtual Wing, we have been looking into ways to make SAMs and networks smarter. 

Would the following be possible in  Skynet-IADS, or would it be possible to implement it in some way?

> In the mission there will be various groups, for example: 
> **_Air Defence Revolutionary Guard Battalion (ADRGB)_**
> 
> **Mission:** 
> Supporting Armor Regiment, Frontline forces
> - 4x SA-15
> - 4x SA-8
> - 1x Dog Ear Radar
> 
> 
> Would it be possible to script it so that only the Dog Ear radar is on, and once any blue aircraft is within range of one of the 1 SA-15, all of the SAM's turn on.  Furthermore, if the Dog Ear Radar is targeted (HARM's), all SAM's go active.
> 
> Also for this request, can this be added to the script using just a prefix or specific text that goes into the groups name in the ME?
> 
> Of course, turning on the SAM's only if the Dog Ear Radar detects anything (so if a aircraft is flying low-level and is masked from the Dog Ear radar, it will not turn on the SAM's as they do not know a aircraft is in the area.
> 
> Intention is to create a smarter and more dangerous Integrated Air Defence System, where they try to lure pilots into their trap, and then open up with all they have.
> So staying on friendly side of the FLOT now makes a lot more sense

Link:
https://github.com/132nd-vWing/OPBR-Brief/issues/9

**Comment by walder** [comment]
Thanks, I hope a lot of DCS mission builders will use the script!

> Would it be possible to script it so that only the Dog Ear radar is on, and once any blue aircraft is within range of one of the 1 SA-15, all of the SAM's turn on. Furthermore, if the Dog Ear Radar is targeted (HARM's), all SAM's go active.

This will happen as you described in the current implementation by default, since a HARM is picked up by the Dog Ear. As soon as an enemy contact is with in firing range, the SAM will light up. In the next release I will add the option for a SAM site to light up at max detection range, max range, and 0-100% of max range.

**Comment by 132ndNeck** [comment]
Great! I look forward to that feature, that will come in handy to make even more sneaky SAM traps.

**Comment by walder** [comment]
Here's a List of planned features:
https://github.com/walder/Skynet-IADS/projects/1
