### ISSUE TITLE
Script dont work with password protected slots

### ISSUE THREAD

**Issue by felipexlr50** [walder/Skynet-IADS#47]
With the new ED protected slots, if the game master slot is password protected, the script fail in addEarlyWarningRadarsByPrefix or setupSAMSitesAndThenActivate
[dcs.log1.log](https://github.com/walder/Skynet-IADS/files/9145069/dcs.log1.log)

**Comment by walder** [comment]
Try using the latest mist version, it seems to be an issue with Mist:
https://github.com/mrSkortch/MissionScriptingTools/issues/68

**Comment by felipexlr50** [comment]
Just tested with the MIST 4.5.107 Hotfix, and its working with protected slots
