### ISSUE TITLE
REQUEST: SAMs beeing able to launch without own radar

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#5]
Would it be possible to add the following features:

- Allowing SAMs to fire on targeting data from other radars in the IADS network? (Sneaky SAM/ambush tactic)

- A SAM site can also fire on a target after its radar have been destroyed, as long as connection node to the IADS network is present, and another SAM site have aquired the target its radar (tracking radar)

**Comment by walder** [comment]
Unfortunately this is not possible with the current DCS scripting implementation.

> Allowing SAMs to fire on targeting data from other radars in the IADS network? (Sneaky SAM/ambush tactic)
The best you can do at the moment is take a long range System like the S-300 and position the launchers far away from the Radar Units. I have no influence on the radar source of a SAM, its sort of hard coded in to the game.

MY IADS just activates the SAM once a target in in range. Usually it is picked up by the SAM radar within a few seconds. That's how I can at least make the SAMs a little more sneaky.

> Allowing SAMs to fire on targeting data from other radars in the IADS network? (Sneaky SAM/ambush tactic)
In DCS SAM Missiles curently just blow up as soon as the Radar of the SAM group goes dark. That would be a very cool tactic. SAM Sites IRL have been known to fire a missile blind and turn on their radar at the last moment for guidance.

When DCS updates their core logic I will try and add it to the IADS.

**Comment by walder** [comment]
In the other hand you will be able to inject false targets in to the IADS. That will trigger the SAMS to go live. 

You could setup a mission in which at a given time false targets are injected to the IADS. So when you are at the right point at the right time you will be able to take out SAM sites from a safe distance.

IRL the US did that with KARI the C3 system developed by France for Iraq:
https://www.ausairpower.net/Analysis-ODS-EW.html

**Comment by 132ndNeck** [comment]
Thanks for the answer. Too bad the DCS scripting implementation would not allow that, it would be a great enhancement and make the IADS very deadly.
