### ISSUE TITLE
BUG: Error when node gets destroyed

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#6]
**BUG:**
Build: Timestamp: 03.03.2020 21:35:37.55
Missionfile: https://www.dropbox.com/s/cvybqk8yxwr728i/Neck_Skynet_test.miz?dl=0

I was testing the script now , and encountered a bug. As a node gets destroyed I get the following error:

![bilde](https://user-images.githubusercontent.com/26002570/75917816-e6c59f00-5e5a-11ea-948e-83d88cabda52.png)

.miz file here:
https://www.dropbox.com/s/cvybqk8yxwr728i/Neck_Skynet_test.miz?dl=0

Mission is setup with a commandcenter
2 x SAM sites, both with a node and a powersupply
2x EW , both with a node and a powersupply

The bug happens both when I destroy the node for the EW and SAM. If I destroy the powersupply it works.

### CODE:

_do
iranIADS = SkynetIADS:create()

---debug settings remove from here on if you do not wan't any output on what the IADS is doing
local iadsDebug = iranIADS:getDebugSettings()
iadsDebug.IADSStatus = true
iadsDebug.samWentDark = true
iadsDebug.contacts = true
iadsDebug.radarWentLive = true
iadsDebug.noWorkingCommmandCenter = true
iadsDebug.ewRadarNoConnection = true
iadsDebug.samNoConnection = true
iadsDebug.jammerProbability = true
iadsDebug.addedEWRadar = true
iadsDebug.hasNoPower = true
---end remove debug ---

iranIADS:addEarlyWarningRadarsByPrefix('EW')
iranIADS:addSamSitesByPrefix('SAM')
iranIADS:activate()	

-- Command Center 1
local commandCenter = StaticObject.getByName("CommandCenter1")
local comPowerSource = StaticObject.getByName("CommandCenter1_power")
iranIADS:addCommandCenter(commandCenter, comPowerSource)

-- SAM Site 2
local powerSource = StaticObject.getByName('SAM_POWER1')
local connectionNode = StaticObject.getByName('SAM_NODE1')
iranIADS:setOptionsForSamSite('SAM-SA-6', powerSource, connectionNode)

-- SAM Site 1
local powerSource = StaticObject.getByName('SAM_POWER2')
local connectionNode = StaticObject.getByName('SAM_NODE2')
iranIADS:setOptionsForSamSite('SAM-SA-6_2', powerSource, connectionNode)

-- Early Warning Radar 1
local powerSource = StaticObject.getByName('EW_POWER1')
local connectionNode = StaticObject.getByName('EW_NODE1')
iranIADS:setOptionsForEarlyWarningRadar('EW-1', powerSource , connectionNode)

-- Early Warning Radar 2
local powerSource = StaticObject.getByName('EW_POWER2')
local connectionNode = StaticObject.getByName('EW_NODE2')
iranIADS:setOptionsForEarlyWarningRadar('EW-2', powerSource , connectionNode)
end_

**Comment by walder** [comment]
thanks, fixed it internally, shouldn't refactor code late at night ;-)
