### ISSUE TITLE
REQUEST: Delay SAM activation when command center disconnect 

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#7]
**REQUEST:**
Build: Timestamp: 03.03.2020 21:35:37.55
Missionfile: https://www.dropbox.com/s/cvybqk8yxwr728i/Neck_Skynet_test.miz?dl=0

In the current version , the SAMs go live immediately after the Commandcenter is disconnected from the IADS (Either by blowing up the Commandcenter or by destroying the powersource)

Would it be possible to add in a delay before the SAMs go live, as it would be more realistic with some delay from an action where the IADS central node is taken out until the SAMs go live.

**Comment by walder** [comment]
yep have that on my list already in the v1.2 backlog. Will implement it on connection node level. So if they lose connection it will take a SAM site some time to figure out its offline.

Also when the command center goes offline, it's a bit robotic otherwise.

**Comment by 132ndNeck** [comment]
Great.
If possible make it customizable, or with some randomization?
