### ISSUE TITLE
BUG: SAM still active when power supply is killed

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#8]
**BUG:**
Build: Timestamp: 03.03.2020 21:35:37.55
Missionfile: https://www.dropbox.com/s/cvybqk8yxwr728i/Neck_Skynet_test.miz?dl=0

After a SAM is active , if the powersupply is destroyed, it does nothing to the SAM group, and it will stay active and still engage aircrafts. 

Example screenshot:
![bilde](https://user-images.githubusercontent.com/26002570/75919820-85073400-5e5e-11ea-825d-af15a898b672.png)

**Comment by walder** [comment]
Thanks, for reporting and testing!

Fixed bug, wrote: testSamSiteLoosesPower sam reported as not active.
