### ISSUE TITLE
Air weapons not tracked correctly by the IADS in latest open beta

### ISSUE THREAD

**Issue by baleBaron** [walder/Skynet-IADS#81]
Since version 2.8.3.37556 of DCS, HARMs or other air weapons are not tracked correctly by the IADS.

After `SkynetIADS.evaluateContacts(self)` is run, only a single HARM or other air weapon is kept in the track file.
`contact:getName()` returns nothing, or a blank name, so when merging contacts all but the first one is rejected.

If I do a dirty workaround like this in skynet-iads.lua on line 494 it works as expected again
`if iadsContact:getDCSRepresentation().id_ == contact:getDCSRepresentation().id_ then`

I am sure someone can come up with a cleaner fix than this. :)

**Comment by MacFlorent** [comment]
I noted the same thing and was about to suggest the same correction. What you propose in your PR seems good to me.
