### ISSUE TITLE
BUG: EW still shows after destroyed

### ISSUE THREAD

**Issue by 132ndNeck** [walder/Skynet-IADS#9]
**BUG:**
Build: Timestamp: 03.03.2020 21:35:37.55
Missionfile: https://www.dropbox.com/s/cvybqk8yxwr728i/Neck_Skynet_test.miz?dl=0

Even after the EW unit is destroyed (see screenshot below), the EW unit shows up in the debugging.

![bilde](https://user-images.githubusercontent.com/26002570/75920325-66556d00-5e5f-11ea-8389-9842901d9929.png)

**Comment by walder** [comment]
I like the way you test the destruction of the EW radar. Debug information is a bit misleading. Technically for the IADS the EW site is still active. Will rewrite that code in the next few days to reflect destruction.

**Comment by walder** [comment]
fixed in latest compiled script.
